SELECT BLOCK_NUMBER,
	ADDRESS,
	CNT,
	NEGATIVE_STARTS,
	NON_NEGATIVE_STARTS,
	UNIQUE_SENDERS,
	CAST(ABS(NEGATIVE_STARTS - NON_NEGATIVE_STARTS) AS FLOAT) / CNT AS BALANCE
FROM
	(SELECT BLOCK_NUMBER,
			ADDRESS,
			COUNT(*) AS CNT,
			COUNT(CASE
				WHEN AMOUNT0 LIKE '-%' THEN 1
				END) AS NEGATIVE_STARTS,
			COUNT(CASE
				WHEN AMOUNT0 NOT LIKE '-%' THEN 1
				END) AS NON_NEGATIVE_STARTS,
			COUNT(DISTINCT SENDER) AS UNIQUE_SENDERS
		FROM SWAPS
		GROUP BY BLOCK_NUMBER,
			ADDRESS) AS COUNTS
WHERE CNT > 4 AND UNIQUE_SENDERS > 1
ORDER BY BALANCE ASC,
	CNT DESC,
	UNIQUE_SENDERS DESC
LIMIT 100;