name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }} # Used for github auth in Azure Static Web Apps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: ./dashboard

      - name: Prisma generate
        run: npx prisma generate
        working-directory: ./dashboard

      - name: Build
        run: npm run build
        working-directory: ./dashboard

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "./dashboard" # App source code path
          api_location: "dashboard/build/server" # Api source code path - optional
          output_location: "build/static" # Built app content directory - optional
